exclusion_list :
  - "a"
  - "able"
  - "about"
  - "above"
  - "according"
  - "accordingly"
  - "across"
  - "actually"
  - "after"
  - "afterwards"
  - "again"
  - "against"
  - "ain't"
  - "all"
  - "allow"
  - "allowed"
  - "allows"
  - "almost"
  - "alone"
  - "along"
  - "already"
  - "also"
  - "although"
  - "always"
  - "am"
  - "among"
  - "amongst"
  - "an"
  - "and"
  - "another"
  - "any"
  - "anybody"
  - "anyhow"
  - "anyone"
  - "anything"
  - "anyway"
  - "anyways"
  - "anywhere"
  - "apart"
  - "apparent"
  - "apparently"
  - "appear"
  - "appeared"
  - "appears"
  - "appreciate"
  - "appreciates"
  - "approach"
  - "approaches"
  - "appropriate"
  - "are"
  - "aren't"
  - "around"
  - "as"
  - "a's"
  - "aside"
  - "ask"
  - "asked"
  - "asking"
  - "asks"
  - "at"
  - "available"
  - "away"
  - "awfully"
  - "b"
  - "back"
  - "backed"
  - "backing"
  - "backs"
  - "based"
  - "be"
  - "became"
  - "because"
  - "become"
  - "becomes"
  - "becoming"
  - "been"
  - "before"
  - "beforehand"
  - "began"
  - "behind"
  - "being"
  - "beings"
  - "believe"
  - "believed"
  - "believes"
  - "below"
  - "beside"
  - "besides"
  - "best"
  - "better"
  - "between"
  - "beyond"
  - "both"
  - "brief"
  - "but"
  - "by"
  - "c"
  - "c_elegans"
  - "caenorhabditis"
  - "caenorhabditis_elegans"
  - "came"
  - "can"
  - "cannot"
  - "cant"
  - "can't"
  - "certain"
  - "certainly"
  - "clear"
  - "clearly"
  - "c'mon"
  - "come"
  - "comes"
  - "concerning"
  - "consequently"
  - "consider"
  - "considered"
  - "considering"
  - "considers"
  - "corresponding"
  - "could"
  - "couldn't"
  - "current"
  - "currently"
  - "d"
  - "definitely"
  - "describe"
  - "described"
  - "describes"
  - "despite"
  - "did"
  - "didn't"
  - "differ"
  - "does"
  - "doesn't"
  - "doing"
  - "done"
  - "don't"
  - "downed"
  - "downing"
  - "downs"
  - "downwards"
  - "during"
  - "e"
  - "each"
  - "eg"
  - "either"
  - "elegans"
  - "else"
  - "elsewhere"
  - "ended"
  - "ending"
  - "enough"
  - "entirely"
  - "especially"
  - "et"
  - "etc"
  - "even"
  - "evenly"
  - "ever"
  - "every"
  - "everybody"
  - "everyone"
  - "everything"
  - "everywhere"
  - "ex"
  - "exactly"
  - "examine"
  - "examined"
  - "examines"
  - "example"
  - "except"
  - "f"
  - "fact"
  - "facts"
  - "far"
  - "felt"
  - "few"
  - "find"
  - "finds"
  - "first"
  - "followed"
  - "following"
  - "follows"
  - "for"
  - "former"
  - "formerly"
  - "found"
  - "from"
  - "full"
  - "fully"
  - "further"
  - "furthered"
  - "furthering"
  - "furthermore"
  - "furthers"
  - "g"
  - "gave"
  - "general"
  - "generally"
  - "get"
  - "gets"
  - "getting"
  - "give"
  - "given"
  - "gives"
  - "goes"
  - "going"
  - "gone"
  - "good"
  - "goods"
  - "got"
  - "gotten"
  - "great"
  - "greater"
  - "greatest"
  - "greetings"
  - "h"
  - "had"
  - "hadn't"
  - "happens"
  - "hardly"
  - "has"
  - "hasn't"
  - "have"
  - "haven't"
  - "having"
  - "he"
  - "hello"
  - "help"
  - "hence"
  - "her"
  - "here"
  - "hereafter"
  - "hereby"
  - "herein"
  - "here's"
  - "hereupon"
  - "hers"
  - "herself"
  - "he's"
  - "hi"
  - "high"
  - "higher"
  - "highest"
  - "him"
  - "himself"
  - "his"
  - "hither"
  - "hopefully"
  - "how"
  - "howbeit"
  - "however"
  - "i"
  - "i'd"
  - "identified"
  - "identifies"
  - "identify"
  - "ie"
  - "if"
  - "ignored"
  - "i'll"
  - "i'm"
  - "immediate"
  - "important"
  - "in"
  - "inasmuch"
  - "inc"
  - "indeed"
  - "indicate"
  - "indicated"
  - "indicates"
  - "insofar"
  - "instead"
  - "interest"
  - "interested"
  - "interesting"
  - "interests"
  - "into"
  - "investigate"
  - "investigated"
  - "investigates"
  - "inward"
  - "is"
  - "isn't"
  - "it"
  - "it'd"
  - "it'll"
  - "its"
  - "it's"
  - "itself"
  - "i've"
  - "j"
  - "just"
  - "k"
  - "keep"
  - "keeps"
  - "kept"
  - "kind"
  - "knew"
  - "know"
  - "known"
  - "knows"
  - "l"
  - "largely"
  - "last"
  - "lately"
  - "later"
  - "latest"
  - "latter"
  - "latterly"
  - "least"
  - "lest"
  - "let's"
  - "like"
  - "liked"
  - "likely"
  - "longer"
  - "longest"
  - "look"
  - "looking"
  - "looks"
  - "ltd"
  - "m"
  - "made"
  - "mainly"
  - "make"
  - "making"
  - "man"
  - "many"
  - "may"
  - "maybe"
  - "me"
  - "mean"
  - "meanwhile"
  - "member"
  - "members"
  - "men"
  - "merely"
  - "might"
  - "more"
  - "moreover"
  - "most"
  - "mostly"
  - "mr"
  - "mrs"
  - "much"
  - "must"
  - "my"
  - "myself"
  - "n"
  - "name"
  - "namely"
  - "nd"
  - "near"
  - "nearly"
  - "necessary"
  - "need"
  - "needed"
  - "needing"
  - "needs"
  - "neither"
  - "never"
  - "nevertheless"
  - "newer"
  - "newest"
  - "next"
  - "nobody"
  - "none"
  - "noone"
  - "nor"
  - "normally"
  - "not"
  - "nothing"
  - "now"
  - "nowhere"
  - "o"
  - "obviously"
  - "of"
  - "off"
  - "often"
  - "oh"
  - "ok"
  - "okay"
  - "old"
  - "older"
  - "oldest"
  - "on"
  - "once"
  - "ones"
  - "only"
  - "onto"
  - "or"
  - "other"
  - "others"
  - "otherwise"
  - "ought"
  - "our"
  - "ours"
  - "ourselves"
  - "over"
  - "overall"
  - "own"
  - "p"
  - "parted"
  - "particular"
  - "particularly"
  - "parting"
  - "per"
  - "perhaps"
  - "place"
  - "placed"
  - "places"
  - "please"
  - "plus"
  - "possible"
  - "present"
  - "presented"
  - "presenting"
  - "presents"
  - "presumably"
  - "probably"
  - "provides"
  - "put"
  - "puts"
  - "q"
  - "quite"
  - "r"
  - "rather"
  - "really"
  - "reasonably"
  - "regard"
  - "regarding"
  - "regardless"
  - "regards"
  - "relatively"
  - "respectively"
  - "result"
  - "resulted"
  - "results"
  - "s"
  - "said"
  - "same"
  - "saw"
  - "say"
  - "saying"
  - "says"
  - "secondly"
  - "see"
  - "seeing"
  - "seem"
  - "seemed"
  - "seeming"
  - "seems"
  - "seen"
  - "sees"
  - "sent"
  - "serious"
  - "seriously"
  - "several"
  - "shall"
  - "she"
  - "should"
  - "shouldn't"
  - "show"
  - "showed"
  - "showing"
  - "shows"
  - "significant"
  - "significantly"
  - "since"
  - "smallest"
  - "some"
  - "somebody"
  - "somehow"
  - "someone"
  - "something"
  - "sometime"
  - "sometimes"
  - "somewhat"
  - "somewhere"
  - "soon"
  - "specified"
  - "specify"
  - "specifying"
  - "still"
  - "studied"
  - "studies"
  - "study"
  - "such"
  - "suggest"
  - "suggested"
  - "suggests"
  - "sure"
  - "t"
  - "take"
  - "taken"
  - "tell"
  - "tends"
  - "th"
  - "than"
  - "thank"
  - "thanks"
  - "thanx"
  - "that"
  - "thats"
  - "that's"
  - "the"
  - "their"
  - "theirs"
  - "them"
  - "themselves"
  - "then"
  - "thence"
  - "there"
  - "thereafter"
  - "thereby"
  - "therefore"
  - "therein"
  - "theres"
  - "there's"
  - "thereupon"
  - "these"
  - "they"
  - "they'd"
  - "they'll"
  - "they're"
  - "they've"
  - "thing"
  - "things"
  - "think"
  - "thinks"
  - "this"
  - "thorough"
  - "thoroughly"
  - "those"
  - "though"
  - "thought"
  - "thoughts"
  - "through"
  - "throughout"
  - "thru"
  - "thus"
  - "to"
  - "today"
  - "together"
  - "too"
  - "took"
  - "toward"
  - "towards"
  - "tried"
  - "tries"
  - "truly"
  - "try"
  - "trying"
  - "u"
  - "un"
  - "under"
  - "unfortunately"
  - "unless"
  - "unlikely"
  - "until"
  - "unto"
  - "upon"
  - "us"
  - "use"
  - "used"
  - "useful"
  - "uses"
  - "using"
  - "usually"
  - "v"
  - "value"
  - "various"
  - "very"
  - "via"
  - "vs"
  - "w"
  - "want"
  - "wanted"
  - "wanting"
  - "wants"
  - "was"
  - "wasn't"
  - "way"
  - "ways"
  - "we"
  - "we'd"
  - "welcome"
  - "well"
  - "we'll"
  - "wells"
  - "went"
  - "were"
  - "we're"
  - "weren't"
  - "we've"
  - "what"
  - "whatever"
  - "what's"
  - "when"
  - "whence"
  - "whenever"
  - "where"
  - "whereafter"
  - "whereas"
  - "whereby"
  - "wherein"
  - "where's"
  - "whereupon"
  - "wherever"
  - "whether"
  - "which"
  - "while"
  - "whither"
  - "who"
  - "whoever"
  - "whole"
  - "whom"
  - "who's"
  - "whose"
  - "why"
  - "will"
  - "willing"
  - "wish"
  - "with"
  - "within"
  - "without"
  - "wonder"
  - "won't"
  - "work"
  - "worked"
  - "working"
  - "works"
  - "would"
  - "wouldn't"
  - "year"
  - "years"
  - "yes"
  - "yet"
  - "you"
  - "you'd"
  - "you'll"
  - "young"
  - "younger"
  - "youngest"
  - "your"
  - "you're"
  - "yours"
  - "yourself"
  - "yourselves"
  - "you've"

gene_exclusion_list:
  - run
  - running
  - cat
  - cated
  - JP
